language: scala
dist: trusty
jdk:
  - oraclejdk8
  - oraclejdk11
  - openjdk8
  - openjdk11
sudo: false
scala:
  - 2.12.10
  - 2.13.1
script:
  - >
    sbt ++$TRAVIS_SCALA_VERSION
    scalafmtCheckAll
    headerCheck test:headerCheck it:headerCheck
    test it:test
